---
title: "Stat 331 Group Project"
author: "Tevan Kim, Will Ton, Eli Newman, Trycia Vong"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r setup}
library(ggplot2)
library(tidyverse)

gdp <- read_csv("GDP_data.csv", col_types = cols(.default = "c"))
co2 <- read_csv("CO2_Data.csv", col_types = cols(.default = "c"))
```
## Combine data into long format and combine

```{r}
gpd_long <- gdp |> 
  pivot_longer(cols = -country,
               names_to = "year",
               values_to = "GDP")


co2_long <- co2 |> 
  pivot_longer(cols = -country,
               names_to = "year",
               values_to = "co2_emissions")


combined_data <- inner_join(gpd_long, co2_long, by = c("country", "year"))
```




## Introduction

Description of data. Hypothesize the relationship between the variables

```{r}

```


## Data Cleaning

```{r}

```

Discuss any data cleaning process and decisions that may impact the analysis.

## Modeling the Relationship between ___ and ____

## Cross-Validation

## Conclusion
**Citations**
